### ISSUE TITLE
Project won't build due to error in ThirdWaveLibrarianApp file

### ISSUE THREAD

**Issue by wileyhodges** [kimsand/ThirdWaveLibrarian#1]
When I try to build the ThirdWaveLibrarian I get a fatal error on lines 37 and 61 of the ThirdWaveLibrarianApp swift file.

The error in both cases is the similar:

37: Cannot call mutating async function 'load(dirURL:)' on actor-isolated property 'banks'
61: Cannot call mutating async function 'load(bank:dirURL:)' on actor-isolated property 'banks'

**Comment by kimsand** [comment]
Thanks! I will look into this. The newer compiler is stricter on concurrency issues than when I wrote this code.

**Comment by kimsand** [comment]
I've updated the code with an extension which allows the code to compile again, and to run as before. A better long-term solution would be to rewrite the data model to use actors for thread safety instead of structs. But for this simple app, I think this fix suffices for now.

**Comment by kimsand** [comment]
Closing this issue.

**Comment by wileyhodges** [comment]
Just as a final note, now builds correctly for me. Thanks for the quick fix. I suspected something like an extension using Binding would be solution, but I wasn't familiar enough with the code to know if that would work.
